### ISSUE TITLE
Runnumber key number padding

### ISSUE THREAD

**Issue by jpazzini** [Mmiglio/FortyMHz#2]
In order to maintain full consistency across Run numbers on the DAQ machine and the ES keys, it could be worth to uniforming the runnumber keys to the format:

`RunXXXXXX `

By moving from 

`.saveToEs("run-{RUN_ID}")`

to something like

`.saveToEs("Run{RUN_ID}")`

Using a 6-digit RUN_ID number

**Comment by Mmiglio** [comment]
Moved index to `run{"RUN_ID"}` since upper case in index name is [not supported](https://github.com/elastic/elasticsearch/issues/29420)
